import { Inter, Satisfy } from 'next/font/google'
import "./globals.css";
import NavBar from '@/components/ui/NavBar';
import Footer from '@/components/ui/Footer';

const inter = Inter({ subsets: ['latin'] });
const satisfy = Satisfy({
  weight: '400',  // or specify other weights you need
  subsets: ['latin'],  // Make sure to use 'bengali' subset
  variable: '--font-satisfy',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${satisfy.variable} antialiased bg-background text-foreground`}>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
